FROM python:3.12-slim

WORKDIR /app

# Copy requirements
COPY requirements.frontend.txt .

# Install dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.frontend.txt

# Copy the app code
COPY . .

# Expose the Streamlit port
EXPOSE 8501

# Start the app
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]